/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lguohsvuarkciiozljva"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxndW9oc3Z1YXJrY2lpb3psanZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDUxMjAsImV4cCI6MjA3NDA4MTEyMH0.Lvg8MtN3FE1P-25XD6FY6FX-mVVJjigwqsqvuHqvXAg"